### ISSUE TITLE
请问支持谷歌得推送吗？

### ISSUE THREAD

**Issue by UTSOURCE** [caoguanjie/cordova-plugin-capacitor-jpush#3]
请问支持谷歌得推送吗？
就是在谷歌商店使用，提供国外用户手机使用

**Comment by caoguanjie** [comment]
您好，这个插件是我司自己集成研发的，只符合国内的手机使用，暂时没有精力集成谷歌推送，其实支持谷歌推送并不难的，你可以阅读代码后，自己尝试集成，期待的你的作品

**Comment by UTSOURCE** [comment]
懂了
